"""
Module 5: PDF Export (Milestone 2 extension)
--------------------------------------------
Renders the structured contract-risk report into a downloadable PDF.

Uses ``fpdf2`` with built-in Helvetica. fpdf2's core fonts only support
Latin-1 glyphs, so we sanitize text before rendering to avoid crashes
on exotic Unicode characters in user-supplied contracts.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from fpdf import FPDF

# Text color tuples (R, G, B) used for risk-level headings.
_RISK_COLORS = {
    "High":    (200,  40,  40),
    "Medium":  (220, 140,  30),
    "Low":     ( 30, 140,  60),
    "Unknown": (110, 110, 110),
}

_DEFAULT_DISCLAIMER = (
    "This report is generated by an AI system for educational and "
    "informational use only. It does not constitute legal advice. "
    "Always consult a qualified attorney before acting on its findings."
)


def build_pdf_report(
    report: List[Dict[str, Any]],
    summary: Optional[Dict[str, Any]] = None,
) -> bytes:
    """Render the full contract-risk report as a PDF byte string.

    Parameters
    ----------
    report:
        List of per-clause analysis dicts from ``run_agent``.
    summary:
        Executive-summary dict (also from ``run_agent``). Optional —
        if omitted, the PDF still renders with only the clause detail.

    Returns
    -------
    bytes
        The fully-rendered PDF, ready for ``st.download_button``.
    """
    pdf = FPDF(format="A4", unit="mm")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    _draw_header(pdf)

    if summary:
        _draw_summary(pdf, summary)

    _draw_clause_details(pdf, report)

    _draw_disclaimer(pdf, summary)

    # fpdf2 returns bytearray; convert for clean typing at the boundary.
    return bytes(pdf.output())


# --------------------------------------------------------------------------
# Sections
# --------------------------------------------------------------------------
def _draw_header(pdf: FPDF) -> None:
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 12, "Contract Risk Assessment Report",
             new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(90, 90, 90)
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    pdf.cell(0, 6, f"Generated: {ts}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)
    pdf.set_draw_color(220, 220, 220)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(4)


def _draw_summary(pdf: FPDF, summary: Dict[str, Any]) -> None:
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 8, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    # Contract overview
    pdf.set_font("helvetica", "", 10)
    overview = summary.get("contract_overview") or "No overview available."
    pdf.multi_cell(0, 5, _sanitize(overview))
    pdf.ln(2)

    # Overall severity
    severity = summary.get("overall_risk_severity", "Unknown")
    color = _RISK_COLORS.get(severity, _RISK_COLORS["Unknown"])
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(*color)
    pdf.cell(0, 6, f"Overall Risk Severity: {severity}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # Top risks
    top_risks = summary.get("top_risks") or []
    if top_risks:
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 6, "Top Risks", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 10)
        for r in top_risks:
            cn = r.get("clause_number", "?")
            desc = r.get("risk_description", "")
            pdf.multi_cell(0, 5, _sanitize(f"  - Clause {cn}: {desc}"))
        pdf.ln(2)

    # Recommended actions
    actions = summary.get("recommended_actions") or []
    if actions:
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 6, "Recommended Actions", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 10)
        for a in actions:
            pdf.multi_cell(0, 5, _sanitize(f"  - {a}"))
        pdf.ln(3)


def _draw_clause_details(pdf: FPDF, report: List[Dict[str, Any]]) -> None:
    # Sort by severity (High first) so the most important findings
    # appear near the top of the detail section.
    order = {"High": 0, "Medium": 1, "Low": 2, "Unknown": 3}
    ordered = sorted(
        report,
        key=lambda e: (order.get(e.get("Risk_Level", "Unknown"), 9),
                       e.get("clause_number", 0)),
    )

    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 8, "Risky Clauses", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    if not ordered:
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(
            0, 5,
            "No high, medium, or unknown-risk clauses were flagged "
            "during automated analysis.",
        )
        pdf.ln(2)
        return

    for entry in ordered:
        level = entry.get("Risk_Level", "Unknown")
        color = _RISK_COLORS.get(level, _RISK_COLORS["Unknown"])

        pdf.set_font("helvetica", "B", 11)
        pdf.set_text_color(*color)
        pdf.cell(
            0, 7,
            _sanitize(f"Clause {entry.get('clause_number', '?')} - {level} Risk"),
            new_x="LMARGIN", new_y="NEXT",
        )
        pdf.set_text_color(0, 0, 0)

        clause_text = entry.get("clause_text", "") or ""
        if len(clause_text) > 800:
            clause_text = clause_text[:800] + "..."

        pdf.set_font("helvetica", "B", 9)
        pdf.cell(0, 5, "Clause Text:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 9)
        pdf.multi_cell(0, 4.5, _sanitize(clause_text))
        pdf.ln(1)

        pdf.set_font("helvetica", "B", 9)
        pdf.cell(0, 5, "Explanation:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 9)
        pdf.multi_cell(0, 4.5, _sanitize(entry.get("Explanation", "") or "—"))
        pdf.ln(1)

        pdf.set_font("helvetica", "B", 9)
        pdf.cell(0, 5, "Suggested Mitigation:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 9)
        pdf.multi_cell(0, 4.5, _sanitize(entry.get("Mitigation", "") or "—"))
        pdf.ln(4)


def _draw_disclaimer(pdf: FPDF, summary: Optional[Dict[str, Any]]) -> None:
    pdf.ln(4)
    pdf.set_draw_color(220, 220, 220)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(110, 110, 110)
    disclaimer = (summary or {}).get("disclaimer") or _DEFAULT_DISCLAIMER
    pdf.multi_cell(0, 4, _sanitize(disclaimer))
    pdf.set_text_color(0, 0, 0)


# --------------------------------------------------------------------------
# Text sanitization
# --------------------------------------------------------------------------
def _sanitize(text: Any) -> str:
    """Coerce to str and drop characters outside Latin-1.

    fpdf2's core fonts are Latin-1 only; non-Latin-1 characters raise
    ``UnicodeEncodeError`` during render. We replace them with '?' so
    an exotic character in one clause does not break the whole report.
    """
    s = "" if text is None else str(text)
    # Some common smart-quote replacements for readability.
    replacements = {
        "\u2018": "'", "\u2019": "'",
        "\u201C": '"', "\u201D": '"',
        "\u2013": "-", "\u2014": "-",
        "\u2022": "-", "\u00A0": " ",
    }
    for src, dst in replacements.items():
        s = s.replace(src, dst)
    return s.encode("latin-1", "replace").decode("latin-1")
